app:
  name: "web_app"
  mode: "dev"
  version: "v0.0.2"
  start_time: "2022-07-01"
  machine_id: 1
  port: 8081
log:
  level: "debug"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 7
mysql:
  host: "192.168.1.4"
  port: 3306
  user: "root"
  password: "123456"
  dbname: "bluebell"
  max_open_conns: 20
  max_idle_conns: 10
redis:
  host: "127.0.0.1"
  password: "123456"
  port: 6379
  db: 0
  pool_size: 100

